### ISSUE TITLE
Feature: User Story Tasks

### ISSUE THREAD

**Issue by henryl74** [henryl74/My-First-Agile-Project#6]
**User Story:** In order to provide anonymous feedback as a user, I can choose to hide in the poll response.

## Acceptance Criteria

**a.** The option should be provided as a checkbox.
**b.** The checkbox should be "checked" by default.
**c.** The option should appear next to the submit button.
**d.** After submitting the default submission confirmation should be adjusted to include the user name.

## Tasks:

- [ ] Update the view: the poll design (HTML and CSS) to include the checkbox and to show the same of the submitter 
- [ ] Create a new field in the model to track the username
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test the functionality
