### ISSUE TITLE
Feature: User Story Tasks for the Website Administrator

### ISSUE THREAD

**Issue by henryl74** [henryl74/My-First-Agile-Project#7]
**User Story:** In order to automatically hide the poll as an administrator, I can pick the expiry date while publishing the poll.

## Acceptance Criteria

**a.** The poll should disappear at 11:59 PM on the target date
**b.** The real estate of the "Poll" should be reserved on the home page, a message that says "Satay Tuned, a new poll is coming soon" should appear if no other Poll is active.
**c.** The administrator expiry date should be at least 3 days after the current date.

## Tasks

- [ ] Update the admin module view: the poll design (HMTL and CSS) to include date picker
- [ ] Update the website view: show "Stay tuned, a new poll is coming soon"
- [ ] Create a Javascript function to validate the expire date is at least after 3 days
- [ ] Create a job to check expired Polls everyday at 11:59 PM and Hide them
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test the functionality
